### ISSUE TITLE
Missing citation link

### ISSUE THREAD

**Issue by djtfmartin** [AtlasOfLivingAustralia/ala-wordpress-2019#4]
Apologies if this should be raised elsewhere.

This URL is used in a few places

https://www.ala.org.au/about-the-atlas/terms-of-use/citing-the-atlas/

I guess we need to redirect to 

https://support.ala.org.au/support/solutions/articles/6000195866-how-to-cite-the-ala

**Comment by matthewandrews** [comment]
OK that redirect is active now.
